### PR TITLE
Fix typo in Readme

### PR DESCRIPTION
**Pull request by Gildilocks**
Fixed a minor typo in the readme

### CODE REVIEW

**Comment by dougwilson** [comment]
Oops, totally forgot to merge this and just saw the email from closing it. It no longer gives me the option to reopen / merge, though, to just do it now.

**Comment by dougwilson** [comment]
Actually the commit still loads, so I can merge it without you needing to do anything. Sorry for losing this PR :(

**Comment by Gildilocks** [comment]
Oh whoops! I thought maybe I botched it so I closed it and just resubmitted
a clearer version.

**Comment by dougwilson** [comment]
No problem :) I'll merge that one :)

**Pull request closed without merging**
