### PR TITLE
Added an option to return resultsets as an array type.

### PR DESCRIPTION
**Pull request by ifsnow**
This is for #770 

You can use the `rowsAsArray` option to get the resultsets as an array type.
I hope this helps.

### CODE REVIEW

**Comment by ifsnow** [comment]
@dougwilson It seems to be a good opinion.
You can now set `rowsAsArray` option for each query request.

```js
connection.query({
  sql: 'SELECT ....',
  rowsAsArray: true
}, function (err, rows) {
  ... 
});
```

**Comment by dougwilson** [comment]
Hi @ifsnow sorry for the delay in feedback, I'm struggling a bit to download your pull request using `git am`. Is it possible you can rebase your PR to be on top of the `master` branch of this repository?

**Comment by ifsnow** [comment]
@dougwilson I noticed there are some trouble in my fork. I can't find dresende's commits in mysqljs:master. (https://github.com/mysqljs/mysql/compare/master...ifsnow:master) Perhaps these commits have been reset. I'll work on fixing it. Please wait a minute.

**Comment by ifsnow** [comment]
@dougwilson I fixed my repository and created a new PR.

**Pull request closed without merging**
