### PR TITLE
Add Pool options : `maxWait`, `initialSize`, `minIdle`, `maxIdle`

### PR DESCRIPTION
**Pull request by ifsnow**
I did the work improving the function of the `Pool`.
I will be good if these options(`maxWait`, `initialSize`, `minIdle`, `maxIdle`, ..) were helpful.

This is the just beginning. I will improve continuously.

### CODE REVIEW

**Comment by frxstrem** [comment]
What's the status on this one? This seems like a feature that should have been implemented long ago.

**Comment by dougwilson** [comment]
@frxstrem it was left off waiting for the author to check the tests and rebase. You're welcome to take over this pull request and own getting it working on the latest version of this module if you are interested.

**Comment by ifsnow** [comment]
I'm here to work on this again. Sorry I took too long.
I need some time to catch up with many changes.
I'll be done with it as soon as possible. Please wait a little longer.

**Comment by ifsnow** [comment]
I'm sorry to keep you waiting too long. I posted a new PR( #1591) about this.
I hope this is what others want. :)

**Comment by dougwilson** [comment]
Closing in favor of the new PR with updated code :)

**Pull request closed without merging**
