### PR TITLE
Updated readable-stream to v2.2.6

### PR DESCRIPTION
**Pull request by mcollina**
As titled.

### CODE REVIEW

**Comment by AdriVanHoudt** [comment]
It might be useful to enable something like [greenkeeper](https://greenkeeper.io/)?

**Comment by dougwilson** [comment]
I haven't upgraded it because it's a breaking change... You can see the CI is broken.

**Comment by mcollina** [comment]
I think it is a problem with npm during the install step. readable-stream works fine on node 0.8 with this config https://github.com/nodejs/readable-stream/blob/master/.travis.yml, I'll see if that works here as well, or if there is an easy fix on readable-stream side.
I wonder how readable-stream 1.x works on Node v0.6.

Have you got any plans to remove support for 0.6 and 0.8?

**Comment by dougwilson** [comment]
Hi @mcollina it's still a breaking change if it's going to require users to upgrade their npm version just like it would be if we required then to upgrade their Node.js version.

> Have you got any plans to remove support for 0.6 and 0.8?

I didn't even want to support Node.js 0.6 but added it because of the barrage of Node.js 0.6 issues that coming in because there were OS distros that only had 0.6 in their package manager, and of course this being a low level driver modules, apparently it is very popular among those types of users.

I plan to drop them when 3.0 comes out, but that just needs myself or others to work on the issues tagged with 3.0 milestone for some of the "big bugs" that are lying around.

**Comment by mcollina** [comment]
@dougwilson would you mind restarting the build, now `readable-stream`  just depends using `~`, so the problem we had was fixed.

**Comment by dougwilson** [comment]
Hi @mcollina thanks for the update! I restarted the Travis CI build but it still fails.

**Comment by mcollina** [comment]
@dougwilson travis is passing with `readable-stream`  v2.2.9. 
AppVeyor is failing, but it seems unrelated: https://ci.appveyor.com/project/dougwilson/node-mysql/build/614/job/tg48p3a3xe7639ag.

**Comment by dougwilson** [comment]
Hm, I wonder what changed to increase the flakiness of that test. I fixed it on master, so am merging your PR :) ! I assume that even though this is a major version bump of readable-stream, it won't actually cause any backwards compatibility issues within how we are exposing the streams to users, right?

**Comment by dougwilson** [comment]
Awesome! I'm just trying to determine what I need to add to the change log and what to change in the README regarding this.

**Comment by dougwilson** [comment]
@mcollina I'm reverting this because `readable-stream` just introduced another dependency with a `^` 4 days ago. I don't think that module is willing to provide the version support we are looking for, sorry.

**Comment by mcollina** [comment]
@dougwilson I'll get you a new version. I'm not sure how I can test that still works on .travis.yml

**Comment by dougwilson** [comment]
Yea, if you're using a test framework that doesn't care about old version support, you can't test on old versions. Your testing framework is the largest limiter for the version you can test against. Being from Perl, it's just mind-boggling that tests frameworks in Node.js don't strive to support all possible versions, instead typically only supporting very recent versions, driving modules that use them to have no choice in the versions they can test on.

**Comment by mcollina** [comment]
version 1 of `readable-stream` is unmaintained and ideally unsopported. We cannot test it on CITGM in core as well.

The problem is not really the test framework. The problem is npm itself.

**Comment by dougwilson** [comment]
I thought you were referring to testing the current readable-stream against things like Node.js 0.8 on Travis CI.

**Comment by dougwilson** [comment]
Doing some tests, looks like even through I pinned the specific version of readable-steam in this PR, the reason why mysql is no longer installable is because it depends on a range for string_decoder and that module also introduced a `^` dependency here: https://github.com/rvagg/string_decoder/blob/master/package.json#L7

**Comment by mcollina** [comment]
a new version of both is coming.

**Comment by mcollina** [comment]
@dougwilson it should be fixed, a new version of `string_decoder` has just been released.

**Comment by dougwilson** [comment]
Sweet, the string_decoder update fixed the current master version right away :)

**Comment by mcollina** [comment]
`readable-stream` with 2.2.11 depends on `safe-buffer` using `~` as well.

**Pull request closed without merging**
