### PR TITLE
Updates for nodejs 10 compatibility.

### LINKED ISSUE #2003: [DEP0096] DeprecationWarning
[DEP0096] DeprecationWarning: timers.unenroll() is deprecated. Please use clearTimeout instead.
on mysql/lib/protocol/Protocol.js:  Timers.unenroll(sequence);

NodeJS 10

### PR DESCRIPTION
**Pull request by coreyfarrell**
* Use setTimeout and .refresh if available.
* Enable testing of nodejs 10.2.1.
* Use 'tls.getCiphers()' if available to detect an available cipher for
  testing.

Fixes #2003.

### CODE REVIEW

**Comment by ipengyo** [comment]
When is this version available?

**Comment by dougwilson** [comment]
I plan to release on 6/6

**Comment by dougwilson** [comment]
Sorry for the delay. Working on getting this merged and a release cut tonight with this 🎉

**Comment by dougwilson** [comment]
Sorry, something happened while I was waiting for a CI build on this, and didn't get back to it. Resuming work on this now.

**Comment by coreyfarrell** [comment]
No worries, thanks for looking into this!

**Comment by NormandoHall** [comment]
Any news about this PR?

**Comment by KyleBoyer** [comment]
@dougwilson Have you gotten any time to look at this?

**Comment by dougwilson** [comment]
Yea, last night I finished up fixing a back compat edge case and so am heading home soon and plan to get it all up tonight.

**Comment by KyleBoyer** [comment]
@dougwilson Any new issues?

**Pull request closed without merging**
