### PR TITLE
Copy properties from `sql` object explicitly

### PR DESCRIPTION
**Pull request by blakeembrey**
Closes https://github.com/mysqljs/mysql/issues/2253.

### CODE REVIEW

**Comment by dougwilson** [comment]
Do you think using Object.create would be sufficient but still keep from maintaining a list at that location? Adding a test that represents the issue would enable me to answer my own question vs defer to you, ps :)

**Comment by blakeembrey** [comment]
@dougwilson Yes, pretty sure, assuming no one is iterating over the `Object.keys` elsewhere within the project. Where should I add a test case? I kind of hoped the existing tests of cover this, since I'm not changing functionality.

**Comment by dougwilson** [comment]
> Where should I add a test case?

So the test files are in the `test/` directory. You'll probably wanted to add them under `unit` since these are likely unit tests.

> I kind of hoped the existing tests of cover this, since I'm not changing functionality.

Well, if there was an existing test, then I guess this PR is unneeded? Not sure why the test suite would be passing without your change here if there is already a test in this module's suite?

**Comment by blakeembrey** [comment]
> Well, if there was an existing test, then I guess this PR is unneeded? Not sure why the test suite would be passing without your change here if there is already a test in this module's suite?

Derp, right - let me add this.

**Comment by blakeembrey** [comment]
Added a test that I believe should work given node 0.6's feature set.

**Comment by blakeembrey** [comment]
@dougwilson Bump.

**Comment by dougwilson** [comment]
I plan to have a new minor out next week and will get this in there.

**Pull request merged**
